name: waveclimate
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.3
  - jupyter==1.0.0
  - numpy==1.16.4 
  - netcdf4==1.4.2
  - matplotlib == 3.1.0
  - cmocean==2.0
  - scipy==1.2.1
  - cartopy==0.17.0
